FILTER_OPTIONS = {
    "DVD": ["DVDs & Blu-ray Discs", "DVD"],
    "Blu-ray": ["DVDs & Blu-ray Discs", "Blu-ray"],
    "TV Shows": ["DVDs & Blu-ray Discs", "season"],
    "VHS Tapes": ["VHS Tapes", None],
    "Film Stock": ["Film Stock", None],
    "Other Formats": ["Other Formats", None],

    "Xbox Games": ["Video Games", "xbox"],
    "Nintendo Games": ["Video Games", "nintendo"],
    "Playstation Games": ["Video Games", "playstation"],

    "Xbox Consoles": ["Video Game Consoles", "xbox"],
    "Nintendo Consoles": ["Video Game Consoles", "nintendo"],
    "PlayStation Consoles": ["Video Game Consoles", "playstation"],

    "Controllers & Attachments": ["Controllers & Attachments", None],
    "Video Game Merchandise": ["Video Game Merchandise", None],
    "Headsets": ["Headsets", None],
    "Original Game Cases & Boxes": ["Original Game Cases & Boxes", None],

    "Desktops & All-In-Ones": ["Desktops & All-In-Ones", None],
    "PC Laptops & Netbooks": ["PC Laptops & Netbooks", None],
    "Tablets & eBook Readers": ["Tablets & eBook Readers", None],
    "Apple Laptops": ["Apple Laptops", None],
    "Apple Desktops & All-In-Ones": ["Apple Desktops & All-In-Ones", None],
    "Monitors": ["Monitors", None],
    "Printers": ["Printers", None],
    "Laptop Replacement Parts": ["Laptop Replacement Parts", None],
    "Graphics/Video Cards": ["Graphics/Video Cards", None],
    "Enterprise Networking, Servers": ["Enterprise Networking, Servers", None],

    "Womens's Clothing": ["Womens's Clothing", None],
    "Women's Bags & Handbags": ["Women's Bags & Handbags", None],
    "Girls": ["Girls", None],
    "Boys": ["Boys", None],
    "Men": ["Men", None],
    "Men's Clothing": ["Men's Clothing", None],

    "Baby & Toddler Clothing": ["Baby & Toddler Clothing", None],
    "Sewing": ["Sewing", None],
    "Quilting": ["Quilting", None],
    "Embroidery & Cross Stitch": ["Embroidery & Cross Stitch", None],
    "Kids' Crafts": ["Kids' Crafts", None],
    "Craft Kits": ["Craft Kits", None],

    "Rings": ["Rings", None],
    "Watches": ["Watches", None],
    "Earrings": ["Earrings", None],
    "Bracelets & Charms": ["Bracelets & Charms", None],

    "Textbooks": ["Textbooks", None],
    "Magazines": ["Magazines", None],
    "Books": ["Books", None],
    "Antiquarian & Collectible": ["Antiquarian & Collectible", None],
    "Audiobooks": ["Audiobooks", None],
    "Study Guides & Test Prep": ["Study Guides & Test Prep", None],
    "Dictionaries & Reference": ["Dictionaries & Reference", None],

    "Action Figures": ["Action Figures", None],
    "Fisher Price": ["Fisher Price", None],
    "Disney": ["Disney", None],
    "LEGO (R) Complete Sets & Packs": ["LEGO (R) Complete Sets & Packs", None],
    "LEGO (R) Building Toys": ["LEGO (R) Building Toys", None],
    "LEGO (R) Bricks, Pieces & Parts": ["LEGO (R) Bricks, Pieces & Parts", None],
    "Puzzles": ["Puzzles", None],
    "Electronic Games": ["Electronic Games", None],
    "Models & Kits": ["Models & Kits", None],
    "Cars: Racing, NASCAR": ["Cars: Racing, NASCAR", None],
    "Star Wars": ["Star Wars", None],

    "Sports Trading Cards": ["Sports Trading Cards", None],
    "Non-Sport Trading Cards": ["Non-Sport Trading Cards", None],
    "Trading Card Lots": ["Trading Card Lots", None],
    "Comics": ["Comics", None],
    "Coins": ["Coins", None],
    "Collectible Figures & Bobbleheads": ["Collectible Figures & Bobbleheads", None],
    "Coca-Cola": ["Coca-Cola", None],
    "Postcards": ["Postcards", None],
    "Stamps": ["Stamps", None],

    "Baseball-MLB": ["Baseball-MLB", None],
    "Football-NFL": ["Football-NFL", None],
    "Basketball-NBA": ["Basketball-NBA", None],
    "Hockey-NHL": ["Hockey-NHL", None],

    "Antique (Pre-1900)": ["Antique (Pre-1900)", None],
    "Civil War (1861-65)": ["Civil War (1861-65)", None],
    "Advertising": ["Advertising", None],
    "Records": ["Records", None],
    "Star Wars Collectibles": ["Star Wars Collectibles", None],
    "Patches, Pins & Buttons": ["Patches, Pins & Buttons", None],

    "Football": ["Football", None],
    "Basketball": ["Basketball", None],
    "Baseball": ["Baseball", None],
    "Golf": ["Golf", None],
    "Soccer": ["Soccer", None],
    "Tennis": ["Tennis", None],
    "Cycling": ["Cycling", None],
    "Skateboarding & Longboarding": ["Skateboarding & Longboarding", None],
    "Fishing": ["Fishing", None],
    "Hunting": ["Hunting", None],
    "Ice Skating": ["Ice Skating", None],

    "Candles & Home Fragrance": ["Candles & Home Fragrance", None],
    "Glassware & Drinkware": ["Glassware & Drinkware", None],
    "Flatware, Knives & Cutlery": ["Flatware, Knives & Cutlery", None],
    "Dinnerware & Serveware": ["Dinnerware & Serveware", None],
    "Kitchen Tools & Gadgets": ["Kitchen Tools & Gadgets", None],
    "Coffee, Tea & Espresso Makers": ["Coffee, Tea & Espresso Makers", None],
    "Bakeware": ["Bakeware", None],
    "Cookware": ["Cookware", None],
    "Grills & Griddles": ["Grills & Griddles", None],

    "Wall Décor": ["Wall Décor", None],
    "Furniture": ["Furniture", None],
    "Bedding": ["Bedding", None],
    "Kitchen, Dining & Bar": ["Kitchen, Dining & Bar", None],
    "Small Kitchen Appliances": ["Small Kitchen Appliances", None],

    "Patio & Garden Furniture": ["Patio & Garden Furniture", None],
    "Garden Hand Tools & Equipment": ["Garden Hand Tools & Equipment", None],
    "Plants, Seeds & Bulbs": ["Plants, Seeds & Bulbs", None],
    "Plant Care, Soil & Accessories": ["Plant Care, Soil & Accessories", None],
    "Herbs, Spices & Seasonings": ["Herbs, Spices & Seasonings", None],

    "Art Prints": ["Art Prints", None],
    "Paintings": ["Paintings", None],
    "Art Sculptures": ["Art Sculptures", None],
    "Art Posters": ["Art Posters", None],
    "Mixed Media Art & Collage Art": ["Mixed Media Art & Collage Art", None],
    "Other Art": ["Other Art", None],
    "Art Photographs": ["Art Photographs", None],
    "Art Drawings": ["Art Drawings", None],
    "Art NFTs": ["Art NFTs", None],
    "Textile Art & Fiber Art": ["Textile Art & Fiber Art", None]
}