# Generated by Django 5.2.7 on 2025-10-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebay", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
