# Generated by Django 5.2.7 on 2025-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_item_category_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ebay_id',
            field=models.CharField(default='12212', max_length=100),
            preserve_default=False,
        ),
    ]
