# Generated by Django 5.2.7 on 2025-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0005_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='charities',
            field=models.ManyToManyField(blank=True, to='ebay.charity'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='items',
            field=models.ManyToManyField(blank=True, to='ebay.item'),
        ),
    ]
