# Generated by Django 5.2.7 on 2025-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0007_alter_favoritelist_charities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=' ', upload_to='items'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='charities',
            field=models.ManyToManyField(blank=True, to='ebay.charity'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='items',
            field=models.ManyToManyField(blank=True, to='ebay.item'),
        ),
    ]
