# Generated by Django 5.2.7 on 2025-12-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0009_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
