# Generated by Django 5.2.7 on 2026-01-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0011_add_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_list',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
