# Generated by Django 5.2.7 on 2026-01-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0012_item_category_list_item_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
    ]
