# Generated by Django 5.2.7 on 2026-01-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0013_remove_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='web_url',
            field=models.URLField(max_length=300),
        ),
    ]
