# Generated by Django 5.2.7 on 2026-01-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0017_alter_item_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='web_url',
            field=models.URLField(max_length=450),
        ),
    ]
