# Generated by Django 5.2.7 on 2026-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0018_alter_item_web_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_images',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='condtion',
            field=models.CharField(default='used', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_location',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
