# Generated by Django 5.2.7 on 2026-01-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0019_item_additional_images_item_condtion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='condtion',
            new_name='condition',
        ),
    ]
