# Generated by Django 5.2.7 on 2026-01-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0020_rename_condtion_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=30),
        ),
    ]
