# Generated by Django 5.2.7 on 2026-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0021_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
