# Generated by Django 5.2.7 on 2026-01-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0022_alter_item_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
