# Generated by Django 5.2.7 on 2026-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0023_alter_item_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
