# Generated by Django 5.2.7 on 2026-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0024_alter_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='donation_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
