# Generated by Django 5.2.7 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0025_charity_donation_url_charity_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='donation_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seller_description',
            field=models.TextField(null=True),
        ),
    ]
