# Generated by Django 6.0.8 on 2026-09-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0030_alter_purchase_charity_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_description',
            field=models.TextField(null=True),
        ),
    ]
